
[build]
build-target = "release"

[build.args]
TIER_VERSION = "v0.12.0"

[deploy]
strategy = "bluegreen"

[env]
TIER_DEBUG = "9"

[checks]
[checks.health]
port = 80
type = "http"
interval = "5s"
timeout = "5s"
grace_period = "10s"
method = "get"
path = "/v1/whoami"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

# # Uncomment this section to enable public-facing http service
# #
# # this section makes this service public-facing. it is also configured to scale to 0
# # instances when not in use, this is configurable via the min_machines_running setting.
# [http_service]
# internal_port = 80
# force_https = true
# auto_stop_machines = true
# auto_start_machines = true
# min_machines_running = 0

# [http_service.concurrency]
# type = "requests"
# soft_limit = 200
# hard_limit = 250

# [[http_service.checks]]
# grace_period = "10s"
# interval = "5s"
# method = "GET"
# timeout = "5s"
# path = "/v1/whoami"
