[build.args]
  TIER_VERSION = "v0.6.2"

[deploy]
  strategy = "bluegreen"

[checks]
  [checks.health]
    type = "http"
    method = "get"
    path = "/v1/whoami"
    port = 80

    grace_period = "5s"
    interval = "10s"
    timeout = "5s"
