
[build]
image = "tierrun/tier:v0.12.0"

[experimental]
cmd = ["--live", "-v", "serve", "-addr", ":80"]

[deploy]
strategy = "bluegreen"

[env]
TIER_DEBUG = "9"

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "5s"
interval = "5s"
method = "GET"
timeout = "5s"
path = "/v1/whoami"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
