
[build]
  build-target = "release"

  [build.args]
    TIER_VERSION = "313127f"

[deploy]
  strategy = "bluegreen"

[env]
  TIER_DEBUG = "9"

[checks]
  [checks.health]
    type = "http"
    method = "get"
    path = "/v1/whoami"
    port = 80

    grace_period = "5s"
    interval = "10s"
    timeout = "5s"
